name = "fpl-bot"
type = "javascript"
zone_id = ""
account_id = "e8f15a69dcf800fd8ede7ff4b130e1d5"
route = ""
workers_dev = true
compatibility_date = "2022-01-13"

[build]
command = "yarn install && yarn run build"
[build.upload]
format = "service-worker"
